name: Code Check

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-check:
    name: Run code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: 📥 Download deps
        uses: u0reo/npm-install@fix/restore-failure
        with:
          useRollingCache: true

      - name: Lint
        run: yarn lint:strict

      - name: Type check
        run: yarn typecheck

      - name: Prettier check
        run: yarn format:check

      - name: Run jest
        run: yarn test